# Generated by Django 3.0.2 on 2020-01-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=8, verbose_name='Ação')),
                ('dividendos', models.FloatField(verbose_name='Dividendos')),
                ('cotas', models.IntegerField(verbose_name='Cotas')),
                ('valor_cota', models.FloatField(verbose_name='Valor por cota')),
            ],
        ),
    ]
